import pyautogui
import time

pyautogui.click(173,234)
pyautogui.hotkey('ctrl', 'l')
pyautogui.press("up")
pyautogui.press("enter")
time.sleep(0.15)
pyautogui.click(785,143)
pyautogui.hotkey('ctrl', 'l')
pyautogui.press("up")
pyautogui.press("enter")
time.sleep(0.15)
pyautogui.click(166,912)
pyautogui.hotkey('ctrl', 'l')
pyautogui.press("up")
pyautogui.press("enter")
time.sleep(0.15)
pyautogui.click(1329,171)
pyautogui.hotkey('ctrl', 'l')
pyautogui.press("up")
pyautogui.press("enter")
time.sleep(0.15)
pyautogui.click(864,1011)
pyautogui.hotkey('ctrl', 'l')
pyautogui.press("up")
pyautogui.press("enter")
time.sleep(0.15)
pyautogui.click(1537,190)
pyautogui.hotkey('ctrl', 'l')
pyautogui.press("up")
pyautogui.press("enter")
time.sleep(0.15)
pyautogui.click(1680, 1010)
pyautogui.hotkey('ctrl', 'l')
pyautogui.press("up")
pyautogui.press("up")